//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Globals
// {
//
//   float4 _MainTex_ST;                // Offset:   32 Size:    16 [unused]
//   float4 _Color;                     // Offset:   48 Size:    16
//   float4 _Selection;                 // Offset:   64 Size:    16
//   float _Grid;                       // Offset:   80 Size:     4
//   float _Diagnostic;                 // Offset:   84 Size:     4
//   int _GalleryCasterCount;           // Offset:   88 Size:     4
//   float4x4 _GalleryCasterInverse[128];// Offset:   96 Size:  8192
//   float4 _GalleryWindows[4];         // Offset: 8288 Size:    64
//   float3 _GalleryToSun;              // Offset: 8352 Size:    12
//   float _GalleryRoof;                // Offset: 8364 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// sampler_MainTex                   sampler      NA          NA             s0      1 
// _MainTex                          texture  float4          2d             t0      1 
// Globals                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000} }
dcl_constantbuffer CB0[523], dynamicIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_output o0.xyzw
dcl_temps 9
dp3 r0.x, v2.xyzx, v2.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, v2.xyzx
add r0.w, -v1.y, cb0[522].w
div r0.w, r0.w, cb0[522].y
mul r1.xy, r0.wwww, cb0[522].xzxx
add r1.xy, r1.xyxx, v1.xzxx
ge r1.zw, r1.xxxy, cb0[518].xxxz
ge r2.xy, cb0[518].ywyy, r1.xyxx
and r0.w, r1.z, r2.x
and r0.w, r1.w, r0.w
and r0.w, r2.y, r0.w
ge r1.zw, r1.xxxy, cb0[519].xxxz
ge r2.xy, cb0[519].ywyy, r1.xyxx
and r1.z, r1.z, r2.x
and r1.z, r1.w, r1.z
and r1.z, r2.y, r1.z
or r0.w, r0.w, r1.z
ge r1.zw, r1.xxxy, cb0[520].xxxz
ge r2.xy, cb0[520].ywyy, r1.xyxx
and r1.z, r1.z, r2.x
and r1.z, r1.w, r1.z
and r1.z, r2.y, r1.z
or r0.w, r0.w, r1.z
ge r1.zw, r1.xxxy, cb0[521].xxxz
ge r1.xy, cb0[521].ywyy, r1.xyxx
and r1.x, r1.x, r1.z
and r1.x, r1.w, r1.x
and r1.x, r1.y, r1.x
or r0.w, r0.w, r1.x
if_nz r0.w
  mul r1.xyz, r0.xyzx, l(0.012000, 0.012000, 0.012000, 0.000000)
  add r1.xyz, r1.xyzx, v1.xyzx
  mov r0.w, l(0)
  mov r1.w, l(0)
  loop 
    ige r2.x, r0.w, cb0[5].z
    mov r1.w, l(0)
    breakc_nz r2.x
    ishl r2.x, r0.w, l(2)
    mul r2.yzw, r1.xxxx, cb0[r2.x + 6].xxyz
    mul r3.xyz, r1.yyyy, cb0[r2.x + 7].xyzx
    add r2.yzw, r2.yyzw, r3.xxyz
    mul r3.xyz, r1.zzzz, cb0[r2.x + 8].xyzx
    add r2.yzw, r2.yyzw, r3.xxyz
    add r2.yzw, r2.yyzw, cb0[r2.x + 9].xxyz
    mul r3.xyz, cb0[522].xxxx, cb0[r2.x + 6].xyzx
    mul r4.xyz, cb0[522].yyyy, cb0[r2.x + 7].xyzx
    add r3.xyz, r3.xyzx, r4.xyzx
    mul r4.xyz, cb0[522].zzzz, cb0[r2.x + 8].xyzx
    add r3.xyz, r3.xyzx, r4.xyzx
    lt r4.xyz, |r3.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    lt r5.xyz, r3.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    movc r5.xyz, r5.xyzx, l(-0.000001,-0.000001,-0.000001,0), l(0.000001,0.000001,0.000001,0)
    movc r3.xyz, r4.xyzx, r5.xyzx, r3.xyzx
    add r4.xyz, -r2.yzwy, l(-0.500000, -0.500000, -0.500000, 0.000000)
    div r4.xyz, r4.xyzx, r3.xyzx
    add r2.xyz, -r2.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000)
    div r2.xyz, r2.xyzx, r3.xyzx
    min r3.xyz, r2.xyzx, r4.xyzx
    max r2.xyz, r2.xyzx, r4.xyzx
    max r2.w, r3.y, r3.x
    max r2.w, r3.z, r2.w
    min r2.x, r2.y, r2.x
    min r2.x, r2.z, r2.x
    max r2.y, r2.w, l(0.001000)
    ge r2.x, r2.x, r2.y
    if_nz r2.x
      mov r1.w, l(-1)
      break 
    endif 
    iadd r0.w, r0.w, l(1)
    mov r1.w, r2.x
  endloop 
  if_z r1.w
    eq r0.w, l(2.000000), cb0[517].w
    if_nz r0.w
      mul r2.xyz, r1.xxxx, cb0[514].xyzx
      mul r1.xyw, r1.yyyy, cb0[515].xyxz
      add r1.xyw, r1.xyxw, r2.xyxz
      mul r2.xyz, r1.zzzz, cb0[516].xyzx
      add r1.xyz, r1.xywx, r2.xyzx
      add r1.xyz, r1.xyzx, cb0[517].xyzx
      mul r2.xyz, cb0[522].xxxx, cb0[514].xyzx
      mul r3.xyz, cb0[522].yyyy, cb0[515].xyzx
      add r2.xyz, r2.xyzx, r3.xyzx
      mul r3.xyz, cb0[522].zzzz, cb0[516].xyzx
      add r2.xyz, r2.xyzx, r3.xyzx
      lt r3.xy, |r2.xzxx|, l(0.000000, 0.000000, 0.000000, 0.000000)
      lt r3.zw, l(0.000000, 0.000000, 0.800000, 0.800000), |r1.xxxz|
      add r4.xy, -r1.xxxx, l(-0.800000, 0.800000, 0.000000, 0.000000)
      div r4.xy, r4.xyxx, r2.xxxx
      min r0.w, r4.y, r4.x
      max r5.x, r0.w, l(0.000000)
      max r0.w, r4.y, r4.x
      min r5.y, r0.w, l(100000002004087734272.000000)
      movc r4.xy, r3.xxxx, l(0,100000002004087734272.000000,0,0), r5.xyxx
      and r3.xz, r3.zzwz, r3.xxyx
      if_z r3.x
        lt r0.w, |r2.y|, l(0.000000)
        lt r1.w, l(1.060000), |r1.y|
        add r4.zw, -r1.yyyy, l(0.000000, 0.000000, -1.060000, 1.060000)
        div r4.zw, r4.zzzw, r2.yyyy
        min r2.w, r4.w, r4.z
        max r5.x, r2.w, r4.x
        max r2.w, r4.w, r4.z
        min r5.y, r2.w, r4.y
        movc r4.xy, r0.wwww, r4.xyxx, r5.xyxx
        and r0.w, r0.w, r1.w
        mov r3.x, r0.w
      else 
        mov r0.w, l(-1)
      endif 
      not r0.w, r0.w
      not r1.w, r3.x
      and r0.w, r0.w, r1.w
      movc r1.w, r0.w, r3.z, r3.x
      if_z r1.w
        add r3.xz, -r1.zzzz, l(-0.800000, 0.000000, 0.800000, 0.000000)
        div r3.xz, r3.xxzx, r2.zzzz
        min r1.w, r3.z, r3.x
        max r5.x, r1.w, r4.x
        max r1.w, r3.z, r3.x
        min r5.y, r1.w, r4.y
        movc r3.xy, r3.yyyy, r4.xyxx, r5.xyxx
        movc r3.xy, r0.wwww, r3.xyxx, r4.xyxx
        ge r0.w, r3.y, r3.x
        if_nz r0.w
          add r0.w, r3.x, l(-0.010000)
          max r0.w, r0.w, l(0.000000)
          mul r3.xyz, r0.wwww, r2.xyzx
          add r1.xyz, r1.xyzx, r3.xyzx
          ftoi r0.w, cb0[514].w
          ftoi r1.w, cb0[515].w
          ishl r2.w, r1.w, l(2)
          lt r3.x, |r2.y|, l(0.000000)
          not r3.x, r3.x
          mul r3.yz, r2.xxzx, r2.xxzx
          add r3.y, r3.z, r3.y
          mul r3.zw, r2.xxxz, r1.xxxz
          add r3.z, r3.w, r3.z
          mul r4.xy, r1.xzxx, r1.xzxx
          add r3.w, r4.y, r4.x
          mov r4.x, cb0[r2.w + 6].x
          mov r4.y, cb0[r2.w + 7].x
          mov r4.zw, l(0,0,0,1)
          mov r5.x, l(0)
          loop 
            uge r5.y, r4.w, r0.w
            mov r5.x, l(0)
            breakc_nz r5.y
            ushr r5.y, r4.w, l(1)
            ushr r5.z, r4.w, l(3)
            and r5.y, r5.y, l(3)
            iadd r5.z, r1.w, r5.z
            ishl r5.z, r5.z, l(2)
            dp4 r6.x, cb0[r5.z + 6].xyzw, icb[r5.y + 0].xyzw
            dp4 r6.y, cb0[r5.z + 7].xyzw, icb[r5.y + 0].xyzw
            dp4 r7.x, cb0[r5.z + 8].xyzw, icb[r5.y + 0].xyzw
            dp4 r7.y, cb0[r5.z + 9].xyzw, icb[r5.y + 0].xyzw
            and r5.y, r4.w, l(1)
            movc r5.yz, r5.yyyy, r7.xxyx, r6.xxyx
            add r5.w, -r4.y, r5.z
            lt r6.x, |r5.w|, l(0.000001)
            if_z r6.x
              min r6.x, r4.y, r5.z
              max r6.y, r4.y, r5.z
              add r6.z, -r4.x, r5.y
              div r5.w, r6.z, r5.w
              add r6.z, r1.y, -r4.y
              mul r6.z, r5.w, r6.z
              add r6.z, r4.x, r6.z
              mul r5.w, r2.y, r5.w
              mul r6.w, r5.w, r5.w
              mul r5.w, r5.w, r6.z
              add r5.w, r3.z, -r5.w
              mul r5.w, r5.w, l(2.000000)
              mul r6.z, r6.z, r6.z
              add r6.zw, r3.wwwy, -r6.zzzw
              lt r7.x, |r6.w|, l(0.000000)
              add r6.xy, r6.xyxx, l(-0.000010, 0.000010, 0.000000, 0.000000)
              if_z r7.x
                mul r7.x, r5.w, r5.w
                mul r7.yz, r6.wwww, l(0.000000, 4.000000, 2.000000, 0.000000)
                mul r7.y, r6.z, r7.y
                add r7.x, -r7.y, r7.x
                lt r7.y, r7.x, l(0.000000)
                sqrt r7.x, r7.x
                lt r7.w, r5.w, l(0.000000)
                movc r7.x, r7.w, -r7.x, r7.x
                add r7.x, r5.w, r7.x
                mul r7.x, r7.x, l(-0.500000)
                lt r7.w, |r7.x|, l(0.000000)
                div r7.z, -r5.w, r7.z
                mul r8.x, r2.y, r7.z
                add r8.x, r1.y, r8.x
                lt r7.z, l(0.000100), r7.z
                ge r8.y, r8.x, r6.x
                and r7.z, r7.z, r8.y
                ge r8.x, r6.y, r8.x
                and r7.z, r7.z, r8.x
                div r6.w, r7.x, r6.w
                mul r8.x, r2.y, r6.w
                add r8.x, r1.y, r8.x
                lt r6.w, l(0.000100), r6.w
                ge r8.y, r8.x, r6.x
                and r6.w, r6.w, r8.y
                ge r8.x, r6.y, r8.x
                and r6.w, r6.w, r8.x
                div r7.x, r6.z, r7.x
                mul r8.x, r2.y, r7.x
                add r8.x, r1.y, r8.x
                lt r7.x, l(0.000100), r7.x
                ge r8.y, r8.x, r6.x
                and r7.x, r7.x, r8.y
                ge r8.x, r6.y, r8.x
                and r7.x, r7.x, r8.x
                or r6.w, r6.w, r7.x
                movc r6.w, r7.w, r7.z, r6.w
                movc r6.w, r7.y, l(0), r6.w
              else 
                lt r7.x, l(0.000000), |r5.w|
                div r5.w, -r6.z, r5.w
                mul r6.z, r2.y, r5.w
                add r6.z, r1.y, r6.z
                lt r5.w, l(0.000100), r5.w
                ge r6.x, r6.z, r6.x
                and r5.w, r5.w, r6.x
                ge r6.x, r6.y, r6.z
                and r5.w, r5.w, r6.x
                and r6.w, r5.w, r7.x
              endif 
            else 
              add r5.w, -r1.y, r4.y
              div r5.w, r5.w, r2.y
              ge r6.x, l(0.000100), r5.w
              not r6.x, r6.x
              mul r6.yz, r2.xxzx, r5.wwww
              add r6.yz, r1.xxzx, r6.yyzy
              mul r6.yz, r6.yyzy, r6.yyzy
              add r5.w, r6.z, r6.y
              mul r6.y, r4.x, r4.x
              mul r6.z, r5.y, r5.y
              min r7.x, r6.z, r6.y
              ge r7.x, r5.w, r7.x
              max r6.y, r6.z, r6.y
              ge r5.w, r6.y, r5.w
              and r6.x, r6.x, r7.x
              and r6.x, r3.x, r6.x
              and r6.w, r5.w, r6.x
            endif 
            if_nz r6.w
              mov r4.z, l(-1)
              mov r5.x, l(-1)
              break 
            endif 
            mov r4.xy, r5.yzyy
            iadd r4.w, r4.w, l(1)
            mov r5.x, r6.w
            mov r4.z, l(0)
          endloop 
          and r0.w, r4.z, r5.x
        else 
          mov r0.w, l(0)
        endif 
      else 
        mov r0.w, l(0)
      endif 
    else 
      mov r0.w, l(0)
    endif 
    movc r0.w, r0.w, l(0), l(1.000000)
  else 
    mov r0.w, l(0)
  endif 
else 
  mov r0.w, l(0)
endif 
lt r1.x, l(0.500000), cb0[5].y
if_nz r1.x
  mov o0.xyz, r0.wwww
  mov o0.w, l(1.000000)
  ret 
endif 
sample r1.xyzw, v3.xyxx, t0.xyzw, s0
mul r1.xyz, r1.xyzx, cb0[3].xyzx
dp3 r1.w, r0.xyzx, l(0.298753, 0.853579, -0.426790, 0.000000)
max r1.w, r1.w, l(0.000000)
mul r1.w, r1.w, l(0.220000)
add r1.w, r1.w, l(0.780000)
mul r2.xyz, r1.wwww, l(0.210000, 0.300000, 0.340000, 0.000000)
dp3 r0.x, r0.xyzx, cb0[522].xyzx
max r0.x, r0.x, l(0.000000)
mul r0.x, r0.x, l(0.200000)
add r0.x, r0.x, l(0.800000)
mul r3.xyz, r0.xxxx, l(1.050000, 0.900000, 0.660000, 0.000000)
add r3.xyz, -r2.xyzx, r3.xyzx
mul r0.xzw, r0.wwww, r3.xxyz
add r0.xzw, r0.xxzw, r2.xxyz
mul r0.xzw, r0.xxzw, r1.xxyz
lt r1.x, l(0.500000), cb0[5].x
lt r0.y, l(0.900000), r0.y
and r0.y, r0.y, r1.x
div r1.xy, v1.xzxx, l(2.000000, 2.000000, 0.000000, 0.000000)
frc r1.xy, r1.xyxx
add r1.xy, r1.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
max r1.x, |r1.y|, |r1.x|
ge r1.x, r1.x, l(0.493000)
movc r1.x, r1.x, l(0.860000), l(1.000000)
mul r1.xyz, r0.xzwx, r1.xxxx
movc r0.xyz, r0.yyyy, r1.xyzx, r0.xzwx
add o0.xyz, r0.xyzx, cb0[4].xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 314 instruction slots used
